### ISSUE TITLE
can't deploy: Resource invalid: source New file does not have the original extension

### ISSUE THREAD

**Issue by lcx** [locomotivecms/engine#1200]
when trying to deploy I get this error for some pages. 
This seems to have happened after upgrading locomotive, currently running git commit cf4855fdb53cbc0212786050148bbe8ad3b178ec

```
  persisting stylesheets/application.css [failed]
    Resource invalid: source New file does not have the original extension
```

I'm not sure what locomotive is trying to tell me with this error. 
If I remove the page and redeploy from scratch, everything is ok again.

**Comment by lcx** [comment]
to solve this issue one could do following: 

```
wagon delete demo theme_assets
```

which deletes all assets, after that deploy again and it works without having to delete the whole site.

**Comment by did** [comment]
hi @lcx, solved by this commit: https://github.com/locomotivecms/engine/commit/0866e9fcb14f13c98fb0429c46b8aa428b9e885c. Please install the 3.3.0.rc2 version.

**Comment by DonKoko** [comment]
I am reporting this as the issue still persists with me. I tried on a few different websites and on each one of them it happens, on a kind or random basis, meaning that a different file faces the issue. Most of the times js.
One one website i deleted all assets from the engine using the `wagon delete` and when i redeployed the issue is even bigger. My CSS is broken and this is what I get in the browser console:
```
[Error] Did not parse stylesheet at 'https://whale-engine.s3-eu-west-1.amazonaws.com/sites/5774da8e38abae03201d27ea/theme/stylesheets/plugins/font-awesome/css/font-awesome.css?1491327397' because non CSS MIME types are not allowed in strict mode.
[Error] Did not parse stylesheet at 'https://whale-engine.s3-eu-west-1.amazonaws.com/sites/5774da8e38abae03201d27ea/theme/stylesheets/plugins/bootstrap/css/bootstrap.min.css?1491327397' because non CSS MIME types are not allowed in strict mode.
```

**Comment by lcx** [comment]
@DonKoko did you upgrade to 3.3.0.rc2? Was just about to do that but if you still have the same issue I will rather wait with the update.

**Comment by did** [comment]
@lcx right, my patch was unfortunately solving one side of the issue.

**Comment by DonKoko** [comment]
@lcx I did, and as Did said we found some other issues so did is working on fixing it.

**Comment by lcx** [comment]
just a quick update, deleted the assets pushed an now seeing these issues: 

```
Warning: Unable to compress and minify it, error: Invalid CSS after "": expected selector, was "25%,75%"
```

now I'm doomed. need to deploy new page today. 
deleting the site and recreating doesn't solve the issue. Wondering if I should roll back a locomotive version or wait for a fix.

**Comment by DonKoko** [comment]
I just rolled back and everything was fine after that. If you are using Heroku rolling back should be pretty straightforward as well.

Mobile: +359 886 816 337
Twitter: @emmision_

Моля, помислете за околната среда преди да принтирате този е-мейл.
Please consider the environment before printing this e-mail.

**Comment by lcx** [comment]
Na, I'm more the self hosted guy. Just rented half a rack and bought my own server, I know, crazy. 
I do have backups, should not be an issue. Problem is that I have somewhere around 20 Sites on that locomotive. 
I will see if I can "abuse" my testserver which has an older version and deploy this one page over there or if the customer can wait a couple of days.

**Comment by manuchap** [comment]
A quick workaround that worked for me (on amazonS3) was to upload the files manually from the s3 managment console and then select the javascript folder and click on more->make public

**Comment by did** [comment]
it was a bug on Wagon 2.4.0. The v2.4.1 version solves this issue but it requires the developer to delete the remote theme assets (wagon delete <env> -r theme_assets -v) and re-deploy them.
